// Estados do Brasil
export const BRAZIL_STATES = [
  { value: "AC", label: "Acre" },
  { value: "AL", label: "Alagoas" },
  { value: "AP", label: "Amapá" },
  { value: "AM", label: "Amazonas" },
  { value: "BA", label: "Bahia" },
  { value: "CE", label: "Ceará" },
  { value: "DF", label: "Distrito Federal" },
  { value: "ES", label: "Espírito Santo" },
  { value: "GO", label: "Goiás" },
  { value: "MA", label: "Maranhão" },
  { value: "MT", label: "Mato Grosso" },
  { value: "MS", label: "Mato Grosso do Sul" },
  { value: "MG", label: "Minas Gerais" },
  { value: "PA", label: "Pará" },
  { value: "PB", label: "Paraíba" },
  { value: "PR", label: "Paraná" },
  { value: "PE", label: "Pernambuco" },
  { value: "PI", label: "Piauí" },
  { value: "RJ", label: "Rio de Janeiro" },
  { value: "RN", label: "Rio Grande do Norte" },
  { value: "RS", label: "Rio Grande do Sul" },
  { value: "RO", label: "Rondônia" },
  { value: "RR", label: "Roraima" },
  { value: "SC", label: "Santa Catarina" },
  { value: "SP", label: "São Paulo" },
  { value: "SE", label: "Sergipe" },
  { value: "TO", label: "Tocantins" },
];

// Principais cidades por estado
export const CITIES_BY_STATE: Record<string, Array<{ value: string; label: string }>> = {
  RJ: [
    { value: "rio-de-janeiro", label: "Rio de Janeiro" },
    { value: "niteroi", label: "Niterói" },
    { value: "sao-goncalo", label: "São Gonçalo" },
    { value: "duque-de-caxias", label: "Duque de Caxias" },
    { value: "nova-iguacu", label: "Nova Iguaçu" },
    { value: "petropolis", label: "Petrópolis" },
    { value: "campos-dos-goytacazes", label: "Campos dos Goytacazes" },
  ],
  SP: [
    { value: "sao-paulo", label: "São Paulo" },
    { value: "campinas", label: "Campinas" },
    { value: "guarulhos", label: "Guarulhos" },
    { value: "santos", label: "Santos" },
    { value: "ribeirao-preto", label: "Ribeirão Preto" },
    { value: "sorocaba", label: "Sorocaba" },
    { value: "sao-jose-dos-campos", label: "São José dos Campos" },
  ],
  RS: [
    { value: "porto-alegre", label: "Porto Alegre" },
    { value: "caxias-do-sul", label: "Caxias do Sul" },
    { value: "pelotas", label: "Pelotas" },
    { value: "canoas", label: "Canoas" },
    { value: "santa-maria", label: "Santa Maria" },
    { value: "gravatai", label: "Gravataí" },
    { value: "viamao", label: "Viamão" },
  ],
};
