export type ColorOption = { value: string; label: string };

export const dialColorOptions: ColorOption[] = [
  { value: "", label: "Selecione..." },
  { value: "Black", label: "Preto" },
  { value: "White", label: "Branco" },
  { value: "Silver", label: "Prata" },
  { value: "Gold", label: "Dourado" },
  { value: "Blue", label: "Azul" },
  { value: "Green", label: "Verde" },
  { value: "Red", label: "Vermelho" },
  { value: "Brown", label: "Castanho" },
  { value: "Gray", label: "Cinzento" },
  { value: "Beige", label: "Champanhe" },
  { value: "Pink", label: "Rosa" },
  { value: "Orange", label: "Laranja" },
  { value: "Yellow", label: "Amarelo" },
  { value: "Bordeaux", label: "Bordeaux" },
  { value: "Turquoise", label: "Turquesa" },
  { value: "Bronze", label: "Bronze" },
  { value: "MotherOfPearl", label: "Madrepérola" },
  { value: "Meteorite", label: "Meteorito" },
  { value: "Skeleton", label: "Esqueletizado" },
];

export const caseColorOptions: ColorOption[] = [
  { value: "", label: "Selecione..." },
  { value: "Silver", label: "Prata" },
  { value: "Steel", label: "Aço" },
  { value: "Gold", label: "Dourado" },
  { value: "RoseGold", label: "Ouro rosé" },
  { value: "YellowGold", label: "Ouro amarelo" },
  { value: "WhiteGold", label: "Ouro branco" },
  { value: "Bronze", label: "Bronze" },
  { value: "Black", label: "Preto" },
  { value: "Blue", label: "Azul" },
  { value: "Green", label: "Verde" },
  { value: "Gray", label: "Cinzento" },
  { value: "Titanium", label: "Titânio" },
  { value: "Ceramic", label: "Cerâmica" },
  { value: "Carbon", label: "Carbono" },
  { value: "Platinum", label: "Platina" },
];

export const braceletColorOptions: ColorOption[] = [
  { value: "", label: "Selecione..." },
  { value: "Black", label: "Preto" },
  { value: "Brown", label: "Castanho" },
  { value: "Blue", label: "Azul" },
  { value: "Gray", label: "Cinzento" },
  { value: "Green", label: "Verde" },
  { value: "Beige", label: "Champanhe" },
  { value: "White", label: "Branco" },
  { value: "Gold", label: "Dourado" },
  { value: "Silver", label: "Prata" },
  { value: "Red", label: "Vermelho" },
  { value: "Orange", label: "Laranja" },
  { value: "Yellow", label: "Amarelo" },
  { value: "Bordeaux", label: "Bordeaux" },
  { value: "Navy", label: "Azul-marinho" },
  { value: "Bronze", label: "Bronze" },
  { value: "RoseGold", label: "Ouro rosé" },
  { value: "Transparent", label: "Transparente" },
];

export const braceletMaterialOptions: ColorOption[] = [
  { value: "", label: "Selecione..." },
  { label: "Aço", value: "Aço" },
  { label: "Alumínio", value: "Alumínio" },
  { label: "Banhado a ouro", value: "Banhado a ouro" },
  { label: "Borracha", value: "Borracha" },
  { label: "Cerâmica", value: "Cerâmica" },
  { label: "Cetim", value: "Cetim" },
  { label: "Couro", value: "Couro" },
  { label: "Latão", value: "Latão" },
  { label: "Ouro amarelo", value: "Ouro amarelo" },
  { label: "Ouro branco", value: "Ouro branco" },
  { label: "Ouro rosa", value: "Ouro rosa" },
  { label: "Ouro vermelho", value: "Ouro vermelho" },
  { label: "Ouro/aço", value: "Ouro/aço" },
  { label: "Pele", value: "Pele" },
  { label: "Pele de avestruz", value: "Pele de avestruz" },
  { label: "Pele de cobra", value: "Pele de cobra" },
  { label: "Pele de crocodilo", value: "Pele de crocodilo" },
  { label: "Pele de lagarto", value: "Pele de lagarto" },
  { label: "Pele de tubarão", value: "Pele de tubarão" },
  { label: "Plástico", value: "Plástico" },
  { label: "Platina", value: "Platina" },
  { label: "Prata", value: "Prata" },
  { label: "Silicone", value: "Silicone" },
  { label: "Têxtil", value: "Têxtil" },
  { label: "Titânio", value: "Titânio" },
];
